Res-10
SemExpert/SemExpert_FixSalesDecimals pull request #1
Opened 2018-09-21 16:50 UTC by lcouget

- Se agrega logica para redondeo.
- Se agrega unit test para plugin.

2018-09-25 00:20 UTC, barbazul requested changes

2018-09-25 00:20 UTC, barbazul commented on etc/di.xml
> +
Y este comment????

2018-10-04 13:23 UTC, lcouget commented on etc/di.xml
> +
Quedaron cosas comentadas. Ahi las saqué.

2018-10-04 13:24 UTC, lcouget commented
Se corrige ademas los test de integracion.

2018-10-04 14:01 UTC, barbanet approved these changes

2018-10-05 21:21 UTC, barbazul approved these changes

2018-10-18 19:46 UTC, merged